# Generated by Django 6.0.3 on 2026-04-06 04:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('shelf_location', models.CharField(blank=True, help_text='Specific location in showroom', max_length=200)),
                ('display_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('fee_type', models.CharField(choices=[('monthly', 'Monthly Rent'), ('one_time', 'One Time Fee'), ('commission_only', 'Commission Only'), ('hybrid', 'Hybrid (Rent + Commission)')], default='commission_only', max_length=20)),
                ('agreed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('units_displayed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_units_to_display', models.IntegerField(default=1)),
                ('max_units_to_display', models.IntegerField(blank=True, null=True)),
                ('units_sold', models.IntegerField(default=0)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rent_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_agreements', to='connections.connection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_agreements', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'display_agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('display_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='display.displayagreement')),
            ],
            options={
                'db_table': 'inventory_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('display_start', 'Display Started'), ('display_end', 'Display Ended'), ('sale', 'Sale Made'), ('commission_paid', 'Commission Paid'), ('rent_paid', 'Rent Paid'), ('stock_update', 'Stock Updated'), ('return', 'Product Returned'), ('damage_report', 'Damage Reported')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('display_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='display.displayagreement')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='displayagreement',
            index=models.Index(fields=['status', 'start_date'], name='display_agr_status_aa83e8_idx'),
        ),
        migrations.AddIndex(
            model_name='displayagreement',
            index=models.Index(fields=['showroom', 'status'], name='display_agr_showroo_3b7a17_idx'),
        ),
        migrations.AddIndex(
            model_name='displayagreement',
            index=models.Index(fields=['product', 'status'], name='display_agr_product_bee3b3_idx'),
        ),
    ]
