# Generated by Django 6.0.3 on 2026-04-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_connection_requests', models.BooleanField(default=True)),
                ('email_sales', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_follows', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=True)),
                ('push_connection_requests', models.BooleanField(default=True)),
                ('push_sales', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_follows', models.BooleanField(default=False)),
                ('in_app_all', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('display_request', 'Display Request'), ('display_approved', 'Display Approved'), ('sale_made', 'Sale Made'), ('commission_paid', 'Commission Paid'), ('new_follower', 'New Follower'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('product_review', 'Product Review'), ('agreement_expiring', 'Agreement Expiring'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = more important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
