# Generated by Django 5.2.6 on 2025-10-22 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_business_product_business_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(default=0, help_text='Current number of units available for sale or allocation.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BusinessProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
