# Generated by Django 5.2.6 on 2025-10-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_businessprofile_owner_product_available_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryallocation',
            name='sending_business',
            field=models.ForeignKey(default=10, help_text='The business profile that owns the product (the sender).', on_delete=django.db.models.deletion.CASCADE, related_name='sent_allocations', to='core.businessprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='product',
            field=models.ForeignKey(help_text='The specific product that stock is being allocated from.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations_made', to='core.product'),
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='quantity_allocated',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='quantity_remaining',
            field=models.PositiveIntegerField(help_text='The remaining quantity available at the receiving business.'),
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='receiving_business',
            field=models.ForeignKey(help_text='The business profile that receives this allocation (the receiver).', on_delete=django.db.models.deletion.CASCADE, related_name='received_allocations', to='core.businessprofile'),
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
