# Generated by Django 5.2.6 on 2025-10-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventoryallocation_sending_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='role',
            field=models.CharField(choices=[('PRODUCER', 'Producer/Product Owner'), ('STORE', 'Showroom/Store')], default='STORE', max_length=10),
        ),
    ]
