# Generated by Django 5.2.6 on 2025-10-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryallocation',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated by Sender, Awaiting Receiver/Manager Action'), ('ACCEPTED', 'Accepted, Inventory Transferred'), ('REJECTED', 'Rejected')], default='INITIATED', help_text='Status of the allocation request or transfer.', max_length=10),
        ),
    ]
