# Generated by Django 5.2.6 on 2025-10-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_receiving_business_inventoryallocation_rreceiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryallocation',
            old_name='rreceiver',
            new_name='receiver',
        ),
    ]
