# Generated by Django 6.0.3 on 2026-05-20 12:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcShowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('income', '💰 Income'), ('expense', '💸 Expense'), ('receivable', '📥 Money to Collect'), ('payable', '📤 Money to Pay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in BDT', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(help_text='What was this transaction for?')),
                ('category', models.CharField(choices=[('sales', 'Product Sales'), ('service', 'Service Income'), ('commission', 'Commission'), ('rent', 'Rent'), ('salary', 'Staff Salary'), ('utility', 'Utilities'), ('inventory', 'Inventory Purchase'), ('marketing', 'Marketing'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=50)),
                ('party_name', models.CharField(blank=True, help_text='Who is this transaction with?', max_length=255)),
                ('party_phone', models.CharField(blank=True, help_text='Contact number of the party', max_length=20)),
                ('party_type', models.CharField(choices=[('producer', 'Producer'), ('showroom', 'Showroom'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('other', 'Other')], default='other', max_length=20)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='When did this transaction happen?')),
                ('due_date', models.DateField(blank=True, help_text='When is payment due?', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When was payment completed?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', '⚠️ Overdue')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='How much has been paid so far?', max_digits=12)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, help_text='How much is still due?', max_digits=12, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring transaction?')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('next_recurrence_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes?')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='acshow/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_transactions', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_transactions', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.ForeignKey(blank=True, help_text='Linked product if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_transactions', to='products.product')),
                ('linked_producer', models.ForeignKey(blank=True, help_text='Linked producer if transaction is with a producer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_transactions_as_party', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'acshow_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcShowAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('payment_due', 'Payment Due'), ('collection_due', 'Collection Due'), ('low_cash', 'Low Cash Warning'), ('low_stock', 'Low Stock Alert'), ('overdue', 'Overdue Payment'), ('milestone', 'Business Milestone')], max_length=20)),
                ('priority', models.CharField(choices=[('high', '🔴 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_alerts', to='accounts.businessprofile')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='acshow.acshowtransaction')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'acshow_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_status', models.CharField(choices=[('healthy', '✅ Healthy'), ('caution', '⚠️ Needs Attention'), ('critical', '🚨 Critical')], default='healthy', max_length=20)),
                ('health_score', models.IntegerField(default=100, help_text='Business health score (0-100)')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of dues collected on time', max_digits=5)),
                ('cash_buffer_days', models.IntegerField(default=0, help_text='How many days can business run with current cash?')),
                ('due_pressure', models.IntegerField(default=0, help_text='Number of overdue collections')),
                ('payment_pressure', models.IntegerField(default=0, help_text='Number of urgent payments needed')),
                ('stock_pressure', models.IntegerField(default=0, help_text='Number of low stock items')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_health', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'Business Health',
                'verbose_name_plural': 'Business Health',
                'db_table': 'acshow_health',
            },
        ),
        migrations.CreateModel(
            name='QuickRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('collection', '💰 Collected Money'), ('payment', '💸 Made Payment'), ('sale', '🛒 Recorded Sale'), ('purchase', '📦 Made Purchase'), ('expense', '🧾 Paid Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(help_text="What's this for? (e.g., 'Sold 5 bags of rice')")),
                ('tag', models.CharField(blank=True, help_text="Quick category (e.g., 'daily', 'weekly', 'one-time')", max_length=50)),
                ('party_name', models.CharField(blank=True, help_text='Who is involved?', max_length=255)),
                ('is_paid', models.BooleanField(default=True, help_text='Has the money been paid/received?')),
                ('due_date', models.DateField(blank=True, help_text='If not paid, when is it due?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_quick_records', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_quick_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Record',
                'verbose_name_plural': 'Quick Records',
                'db_table': 'acshow_quick_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcShowCashPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Cash at start of day', max_digits=12)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, help_text='Total money received today', max_digits=12)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, help_text='Total money spent today', max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Cash at end of day', max_digits=12)),
                ('cash_in_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of cash received by category')),
                ('cash_out_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of cash spent by category')),
                ('has_shortfall', models.BooleanField(default=False, help_text='Is there a cash shortage?')),
                ('shortfall_amount', models.DecimalField(decimal_places=2, default=0, help_text='How much cash is missing?', max_digits=12)),
                ('upcoming_payables', models.DecimalField(decimal_places=2, default=0, help_text='Total payments due in next 7 days', max_digits=12)),
                ('upcoming_receivables', models.DecimalField(decimal_places=2, default=0, help_text='Total collections expected in next 7 days', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_cash_positions', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'Cash Position',
                'verbose_name_plural': 'Cash Positions',
                'db_table': 'acshow_cash_positions',
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['business', 'transaction_type', 'status'], name='acshow_tran_busines_e0abae_idx'),
        ),
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['business', 'transaction_date'], name='acshow_tran_busines_128ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['due_date', 'status'], name='acshow_tran_due_dat_f3f78d_idx'),
        ),
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['party_type', 'party_name'], name='acshow_tran_party_t_eb24e5_idx'),
        ),
        migrations.AddIndex(
            model_name='quickrecord',
            index=models.Index(fields=['business', 'entry_type'], name='acshow_quic_busines_0a5c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='quickrecord',
            index=models.Index(fields=['business', 'created_at'], name='acshow_quic_busines_fd14b1_idx'),
        ),
    ]
