# Generated by Django 6.0.3 on 2026-05-21 15:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acshowtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in BDT', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
