# Generated by Django 6.0.3 on 2026-05-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reset_token_user_reset_token_expiry'),
        ('acshow', '0002_alter_acshowtransaction_amount_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acshowtransaction',
            name='category',
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='source',
            field=models.CharField(choices=[('pos', 'POS Terminal'), ('manual', 'Manual Entry'), ('quick', 'Quick Record'), ('showpur', 'Showpur Order'), ('bulk', 'Bulk Import')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='cash_in_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='cash_out_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='has_shortfall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='shortfall_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='total_cash_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='total_cash_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='upcoming_payables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowcashposition',
            name='upcoming_receivables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='cash_buffer_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='collection_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='due_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='health_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='payment_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='stock_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='description',
            field=models.TextField(help_text="What's this for?"),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='party_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, help_text='Bengali name', max_length=100)),
                ('category_type', models.CharField(choices=[('income', '📥 Money In'), ('expense', '📤 Money Out')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_categories', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'acshow_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='transaction_category',
            field=models.ForeignKey(blank=True, help_text='Transaction category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='acshow.transactioncategory'),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='transaction_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acshow.transactioncategory'),
        ),
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['transaction_category'], name='acshow_tran_transac_b4363c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('business', 'name')},
        ),
    ]
