# Generated by Django 6.0.3 on 2026-05-24 12:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0003_remove_acshowtransaction_category_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acshowtransaction',
            name='linked_order',
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product sold or purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_transactions', to='products.product'),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity of product', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='sale_source',
            field=models.CharField(choices=[('pos', '🏪 Own Shop'), ('showroom', '🏬 Showroom'), ('online', '📱 Online'), ('direct', '👤 Direct'), ('consignment', '🤝 Consignment'), ('manual', '📋 Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='sale_type',
            field=models.CharField(choices=[('own', 'Own Product'), ('commission', 'Commission/Consignment')], default='own', max_length=20),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_quick_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='sale_source',
            field=models.CharField(choices=[('pos', '🏪 Own Shop'), ('showroom', '🏬 Showroom'), ('online', '📱 Online'), ('direct', '👤 Direct'), ('consignment', '🤝 Consignment'), ('manual', '📋 Manual')], default='manual', max_length=20),
        ),
    ]
