# Generated by Django 6.0.3 on 2026-05-24 13:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reset_token_user_reset_token_expiry'),
        ('acshow', '0004_remove_acshowtransaction_linked_order_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acshowtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='linked_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_transactions_as_party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='party_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acshow_transactions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='transaction_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='acshow.transactioncategory'),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('customer', '👤 Customer'), ('supplier', '🏭 Supplier'), ('agent', '🤝 Agent')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acshow_contacts', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'acshow_contacts',
                'ordering': ['name'],
                'unique_together': {('business', 'name', 'contact_type')},
            },
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked customer or supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='acshow.contact'),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked customer or supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acshow.contact'),
        ),
    ]
