# Generated by Django 6.0.3 on 2026-05-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0005_alter_acshowtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acshowtransaction',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked customer or supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='connections.contact'),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked customer or supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.contact'),
        ),
    ]
