# Generated by Django 6.0.3 on 2026-05-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0006_alter_acshowtransaction_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acshowtransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acshowtransaction',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', '🕐 Pending Approval'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('pending_edit', '✏️ Edit Pending Approval')], default='pending', max_length=20),
        ),
    ]
