# Generated by Django 6.0.3 on 2026-06-06 05:20 (manually fixed for DB/state divergence)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_acshow_enabled'),
        ('acshow', '0008_transaction_payment_split_and_types'),
        ('connections', '0001_initial'),
        ('ledger', '0001_initial'),
        ('products', '0002_rename_reserved_quantity_product_reserved_dropship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Contact model cleanup ──────────────────────────────────────────────
        # acshow_contacts table never existed in this DB — state-only cleanup.
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterUniqueTogether(name='contact', unique_together=None),
            migrations.RemoveField(model_name='contact', name='business'),
            migrations.DeleteModel(name='Contact'),
        ]),

        # ── TransactionCategory cleanup ────────────────────────────────────────
        # acshow_categories table EXISTS — real DB operations.
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='business',
        ),

        # ── Remove stale columns from acshow_transactions ─────────────────────
        migrations.RemoveField(
            model_name='acshowtransaction',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='acshowtransaction',
            name='linked_producer',
        ),
        migrations.RemoveField(
            model_name='quickrecord',
            name='transaction_category',
        ),

        # ── Remove old indexes ─────────────────────────────────────────────────
        migrations.RemoveIndex(
            model_name='acshowtransaction',
            name='acshow_tran_party_t_eb24e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='acshowtransaction',
            name='acshow_tran_transac_b4363c_idx',
        ),

        # ── Remove old transaction_category FK ────────────────────────────────
        migrations.RemoveField(
            model_name='acshowtransaction',
            name='transaction_category',
        ),

        # ── Drop TransactionCategory table ────────────────────────────────────
        migrations.DeleteModel(
            name='TransactionCategory',
        ),

        # ── Add new account FK (ledger.Account) ───────────────────────────────
        migrations.AddField(
            model_name='acshowtransaction',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transactions',
                to='ledger.account'
            ),
        ),
        migrations.AddField(
            model_name='quickrecord',
            name='account',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ledger.account'
            ),
        ),

        # ── Add new index on account ───────────────────────────────────────────
        migrations.AddIndex(
            model_name='acshowtransaction',
            index=models.Index(fields=['account'], name='acshow_tran_account_062ed2_idx'),
        ),

        # ── Field-level alterations (choices updates etc.) ────────────────────
        migrations.AlterModelOptions(
            name='acshowalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='businesshealth',
            options={'verbose_name': 'Business Health'},
        ),
        migrations.AlterField(
            model_name='acshowalert',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='connections.contact'),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='sale_source',
            field=models.CharField(choices=[('pos', 'Own Shop'), ('showroom', 'Showroom'), ('online', 'Online'), ('direct', 'Direct'), ('consignment', 'Consignment'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_edit', 'Edit Pending Approval')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesshealth',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('caution', 'Needs Attention'), ('critical', 'Critical')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.contact'),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='entry_type',
            field=models.CharField(choices=[('collection', 'Collected Money'), ('payment', 'Made Payment'), ('sale', 'Recorded Sale'), ('purchase', 'Made Purchase'), ('expense', 'Paid Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='sale_source',
            field=models.CharField(choices=[('pos', 'Own Shop'), ('showroom', 'Showroom'), ('online', 'Online'), ('direct', 'Direct'), ('consignment', 'Consignment'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
