# Generated by Django 6.0.3 on 2026-06-11 18:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0010_cost_amount_and_owner_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerwithdrawal',
            options={'ordering': ['-withdrawn_at']},
        ),
        migrations.RenameIndex(
            model_name='ownerwithdrawal',
            new_name='acshow_owne_busines_feba8f_idx',
            old_name='acshow_owne_busines_idx',
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='acshowtransaction',
            name='source',
            field=models.CharField(choices=[('pos', 'POS Terminal'), ('manual', 'Manual Entry'), ('quick', 'Quick Record'), ('showpur', 'Showpur Order'), ('bulk', 'Bulk Import'), ('collection', 'Collection Payment')], default='manual', max_length=20),
        ),
    ]
