# Generated by Django 6.0.3 on 2026-06-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0011_alter_ownerwithdrawal_options_and_more'),
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acshowtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='coa.account'),
        ),
        migrations.AlterField(
            model_name='quickrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.account'),
        ),
    ]
