# Generated by Django 6.0.3 on 2026-06-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_acshow_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('income', 'Money In'), ('expense', 'Money Out'), ('cash_bank', 'My Cash & Bank'), ('receivable', 'Will Collect'), ('payable', 'Will Pay')], max_length=20)),
                ('account_code', models.CharField(blank=True, max_length=10)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='accounts.businessprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='ledger.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'ledger_accounts',
                'ordering': ['order', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
