# Generated by Django 6.0.3 on 2026-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acshow', '0012_alter_acshowtransaction_account_and_more'),
        ('ledger', '0002_add_capital_account_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
