# Generated by Django 6.0.3 on 2026-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acshow_enabled',
            field=models.BooleanField(default=False, help_text='User has access to AcShow financial tools'),
        ),
        migrations.AddField(
            model_name='user',
            name='acshow_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='acshow_trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='acshow_trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
