# Generated by Django 6.0.3 on 2026-06-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acshow_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
