# Generated by Django 6.0.3 on 2026-04-06 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('producer_to_showroom', 'Producer → Showroom'), ('showroom_to_producer', 'Showroom → Producer')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('suggested_product_ids', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('proposed_duration_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shelf_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_connections_as_producer', to=settings.AUTH_USER_MODEL)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_connections_as_showroom', to=settings.AUTH_USER_MODEL)),
                ('connection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='connections.connectionrequest')),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['status', 'created_at'], name='connection__status_6ff6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['from_user', 'to_user'], name='connection__from_us_0a2c66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
