# Generated by Django 6.0.3 on 2026-05-25 18:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_reset_token_user_reset_token_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('producer_to_showroom', 'Producer → Showroom'), ('showroom_to_producer', 'Showroom → Producer')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('suggested_product_ids', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('proposed_duration_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.businessprofile')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests_old', to=settings.AUTH_USER_MODEL)),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.businessprofile')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests_old', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shelf_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_connections_as_producer', to='accounts.businessprofile')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_connections_as_showroom', to='accounts.businessprofile')),
                ('connection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='connections.connectionrequest')),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier for this specific contact record', primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('customer', '👤 Customer'), ('supplier', '🏭 Supplier')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('proprietor_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.businessprofile')),
                ('linked_business', models.ForeignKey(blank=True, help_text='Link to existing ShowPur business if they join', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='accounts.businessprofile')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['company_name'],
            },
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['status', 'created_at'], name='connection__status_6ff6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['from_business', 'to_business'], name='connection__from_bu_977480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('from_business', 'to_business', 'request_type')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['business', 'contact_type'], name='contacts_busines_8beeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['business', 'is_active'], name='contacts_busines_f13245_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contacts_phone_3b79d2_idx'),
        ),
    ]
