# Generated by Django 6.0.3 on 2026-05-26 08:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reserved_quantity',
            new_name='reserved_dropship',
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_type',
            field=models.CharField(choices=[('physical', 'Physical only'), ('dropship', 'Dropship only'), ('both', 'Physical + Dropship')], default='physical', help_text='Controls which display/sale channels are open for this product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_showroom',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Additional image URLs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='DisplayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('physical', 'Physical display'), ('dropship', 'Online / dropship')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('requested_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('accepted_quantity', models.IntegerField(blank=True, null=True)),
                ('agreed_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agreed_display_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_requests', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'display_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('quantity_returned', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_stock', to='products.displayrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_stocks', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'showroom_stock',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('own_shop', 'Own shop / showroom'), ('showroom', 'Displaying showroom'), ('online', 'Online / dropship'), ('pos', 'POS terminal')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_fulfillment', models.BooleanField(default=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
                ('showroom_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.showroomstock')),
            ],
            options={
                'db_table': 'sale_records',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase / restock'), ('production', 'Production'), ('sale', 'Sale'), ('dispatch', 'Dispatched to showroom'), ('return', 'Return'), ('adjustment', 'Manual adjustment'), ('reserved', 'Dropship reserved'), ('unreserved', 'Dropship unreserved')], max_length=20)),
                ('qty', models.IntegerField(help_text='Positive = in, negative = out')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('display_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.displayrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='products.product')),
                ('sale_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.salerecord')),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='displayrequest',
            index=models.Index(fields=['product', 'status'], name='display_req_product_324cad_idx'),
        ),
        migrations.AddIndex(
            model_name='displayrequest',
            index=models.Index(fields=['showroom', 'status'], name='display_req_showroo_5ed78d_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['product', 'channel'], name='sale_record_product_713b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['seller', 'sold_at'], name='sale_record_seller__c2bf74_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['sold_at'], name='sale_record_sold_at_29d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['product', 'timestamp'], name='stock_ledge_product_63df93_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['entry_type'], name='stock_ledge_entry_t_c089e8_idx'),
        ),
    ]
